name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Get dependencies
        run: flutter pub get

      - name: Change APP Logo
        run: |
          flutter pub run flutter_launcher_icons:main 
      - name: Change Package Name
        run: |
          flutter pub run change_app_package_name:main com.racecar.world
      - name: Change APP Name
        run: |
          flutter pub run rename_app:main all="Race Car"
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore ./keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias "upload" -storepass "12345678" -keypass "12345678" -dname "CN=NameOrg, OU=NameOrg, O=NameOrg"
      
      - name: Build app bundle
        run: flutter build appbundle

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab